import type { IconType } from "react-icons";
import {
  FaAward,
  FaBalanceScale,
  FaBell,
  FaBolt,
  FaBroom,
  FaBuilding,
  FaBurn,
  FaCalendarCheck,
  FaCar,
  FaChargingStation,
  FaChartLine,
  FaCheckCircle,
  FaClipboardCheck,
  FaCog,
  FaDoorOpen,
  FaEnvelope,
  FaEuroSign,
  FaExclamationTriangle,
  FaFan,
  FaFaucet,
  FaFileAlt,
  FaFileSignature,
  FaFilter,
  FaFire,
  FaHandshake,
  FaHardHat,
  FaHeadset,
  FaHome,
  FaHouseDamage,
  FaKey,
  FaLayerGroup,
  FaLeaf,
  FaLightbulb,
  FaMapMarkerAlt,
  FaMobileAlt,
  FaPhoneAlt,
  FaPiggyBank,
  FaPlug,
  FaPowerOff,
  FaProjectDiagram,
  FaRegClock,
  FaRegComments,
  FaRegCalendarAlt,
  FaRulerCombined,
  FaSearch,
  FaShieldAlt,
  FaShower,
  FaSink,
  FaSmog,
  FaSnowflake,
  FaStopwatch,
  FaSyncAlt,
  FaTachometerAlt,
  FaTemperatureHigh,
  FaTemperatureLow,
  FaThermometerHalf,
  FaTint,
  FaToilet,
  FaTools,
  FaUserFriends,
  FaUserShield,
  FaUserTie,
  FaVideo,
  FaVolumeUp,
  FaWater,
  FaWifi,
  FaWind,
  FaWrench,
} from "react-icons/fa";

// Les données de contenu (app/data/**) référencent les icônes par clé texte
// plutôt que par composant : les clés sont sérialisables, donc utilisables
// aussi bien dans un composant serveur que client.
export const icons = {
  alert: FaExclamationTriangle,
  award: FaAward,
  balance: FaBalanceScale,
  bell: FaBell,
  bolt: FaBolt,
  broom: FaBroom,
  building: FaBuilding,
  burn: FaBurn,
  calendar: FaRegCalendarAlt,
  calendarCheck: FaCalendarCheck,
  car: FaCar,
  chart: FaChartLine,
  charging: FaChargingStation,
  check: FaCheckCircle,
  clipboard: FaClipboardCheck,
  clock: FaRegClock,
  cog: FaCog,
  comments: FaRegComments,
  damage: FaHouseDamage,
  door: FaDoorOpen,
  envelope: FaEnvelope,
  euro: FaEuroSign,
  fan: FaFan,
  faucet: FaFaucet,
  file: FaFileAlt,
  fileSign: FaFileSignature,
  filter: FaFilter,
  fire: FaFire,
  handshake: FaHandshake,
  hardhat: FaHardHat,
  headset: FaHeadset,
  home: FaHome,
  key: FaKey,
  layers: FaLayerGroup,
  leaf: FaLeaf,
  lightbulb: FaLightbulb,
  map: FaMapMarkerAlt,
  mobile: FaMobileAlt,
  phone: FaPhoneAlt,
  piggy: FaPiggyBank,
  plug: FaPlug,
  power: FaPowerOff,
  pressure: FaTachometerAlt,
  ruler: FaRulerCombined,
  schema: FaProjectDiagram,
  search: FaSearch,
  shield: FaShieldAlt,
  shower: FaShower,
  sink: FaSink,
  smog: FaSmog,
  snowflake: FaSnowflake,
  stopwatch: FaStopwatch,
  sync: FaSyncAlt,
  tempHigh: FaTemperatureHigh,
  tempLow: FaTemperatureLow,
  thermometer: FaThermometerHalf,
  toilet: FaToilet,
  tools: FaTools,
  userShield: FaUserShield,
  userTie: FaUserTie,
  users: FaUserFriends,
  video: FaVideo,
  volume: FaVolumeUp,
  water: FaWater,
  drop: FaTint,
  wifi: FaWifi,
  wind: FaWind,
  wrench: FaWrench,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof icons;

export function Icon({
  name,
  className,
}: {
  name: IconKey;
  className?: string;
}) {
  const Component = icons[name];
  return <Component className={className} aria-hidden="true" />;
}
